module.exports = {
  rules: {
    // "no-async-subscribe"
    // "no-compat"
    // "no-connectable"
    // "no-create"
    // "no-explicit-generics"
    // "no-ignored-notifier"
    // "no-ignored-replay-buffer"
    // "no-ignored-observable"
    // "no-ignored-subscription"
    // "no-ignored-takewhile-value"
    // "no-index"
    // "no-internal"
    // "no-nested-subscribe"
    // "no-sharereplay"
    // "no-subclass"
    // "no-subject-unsubscribe"
    // "no-subject-value"
    // "no-unbound-methods"
    // "no-unsafe-catch"
    // "no-unsafe-first"
    // "no-unsafe-scope"
    // "no-unsafe-subject-next"
    // "no-unsafe-switchmap"
    // "no-unsafe-takeuntil"
    // "throw-error"
  }
};
